import re
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.messages import RemoveMessage


from app.models.ast_structure import NextflowPipelineAST
from app.services.llm import get_llm
from app.services.tools import retrieve_rag_context
from app.services.graph_state import GraphState
from app.services.renderer import render_mermaid_from_json
from app.models.consultant_structure import ConsultantOutput
from app.models.diagram_structure import DiagramData
from app.core.loader import data_loader
from langgraph.store.base import BaseStore

# ==========================================
# 1. SYSTEM PROMPTS
# ==========================================

CONSULTANT_SYSTEM_PROMPT = """You are an Expert Bioinformatics Consultant.
Your job is to talk with the user, check available tools, and design a Nextflow DSL2 pipeline step by step.

# 1. GROUNDING IN RAG CONTEXT (CRITICAL)
You have access to a dynamically retrieved database of templates and components (the RAG Context).
* YOU MUST ONLY SUGGEST TOOLS AND TEMPLATES THAT APPEAR IN THE CURRENT RAG CONTEXT.
* When suggesting options, tell the user exactly what templates and components are available based on the RAG context. 
* Mention the exact component IDs (e.g., `step_1PP_trimming__fastp`) and template IDs so there is no confusion.
* IF IT IS NOT IN THE RAG CONTEXT, IT DOES NOT EXIST. If the user asks for a tool and it is missing from the context, you must tell them: "I do not have a tool for SPAdes in my current database." Do not pretend it exists.

# 2. YOUR WORKFLOW
1. Deeply analyze the AVAILABLE RAG CONTEXT. Look specifically for the `--- COMPONENT: <ID> ---` and `--- TEMPLATE: <ID> ---` headers.
2. Read the user message and the chat history.
3. Reply to the user in plain English (`response_to_user`). Suggest a pipeline flow based ONLY on the retrieved tools.
4. Keep `status` as "CHATTING" while discussing.
5. When the user approves the pipeline, change `status` to "APPROVED".

# 3. POST-GENERATION REVISIONS (CRITICAL)
If the user provides feedback on a pipeline you ALREADY generated (e.g., "Change iVar to Bowtie"):
1. Acknowledge the change.
2. CHECK THE RAG CONTEXT to ensure the new tool is actually available.
3. If you need to discuss it more, set status to "CHATTING".
4. If you immediately understand the change and the tool is in the context, set status to "APPROVED" and output the entirely updated `draft_plan` and `selected_module_ids`.

# 4. WHEN APPROVED
When you set status to "APPROVED", you MUST fill out the following fields based strictly on the RAG context:
1. `draft_plan`: A highly detailed text instruction manual for the Architect Agent. Explain exactly which component IDs to use and how data channels connect.
2. `strategy_selector`: Choose "EXACT_MATCH" if using a template exactly, "ADAPTED_MATCH" if modifying a template, or "CUSTOM_BUILD" if building from scratch.

# 5. ANTI-HALLUCINATION RULES FOR IDs (TAKE A DEEP BREATH)
You MUST extract the exact ID strings from the RAG context for `used_template_id` and `selected_module_ids`. 
- Look precisely at the text following `--- COMPONENT:` or `--- TEMPLATE:`. You MUST copy that exact string.
- DO NOT invent names.
- You MUST ONLY use IDs from the CURRENT RAG CONTEXT OR the IDs already listed in the CURRENT PIPELINE STATE. Do not invent any new ones.
- DO NOT guess prefixes. If the context says `step_1PP_trimming__fastp`, do not write `step_1AS_trimming__fastp`.
- DO NOT use shorthand (e.g., use `step_4TY_lineage__pangolin`, NOT `pangolin`).
- If a tool is not in the RAG context, DO NOT include it in the plan.
"""

ARCHITECT_SYSTEM_PROMPT = """You are the Principal Bioinformatics Architect and Nextflow DSL2 Expert.
Generate a production-ready Nextflow DSL2 pipeline as a **NextflowPipelineAST** JSON object.

# Output Schema

| Field | Type | Description |
|-------|------|-------------|
| `imports` | `[]` | **Leave empty.** Auto-generated by the system. |
| `globals` | `[{{"type","name","value"}}]` | Static `def` constants only (strings/paths). **Quote all values.** |
| `inline_processes` | `[{{"name","script_block",...}}]` | Custom bash-only processes not in RAG context. |
| `sub_workflows` | `[{{"name","take_channels","emit_channels","body_code"}}]` | Reusable workflow modules. |
| `entrypoint` | `{{"body_code"}}` | Main anonymous workflow. Cannot emit. |

Write **raw Nextflow Groovy** in all `body_code` fields. The rendering engine auto-wraps `workflow {{}}`, `take:`, `main:`, `emit:` — **never write these keywords in body_code**.

---

# 1. Data-Shaping Idioms

## 1A. Named Emits
Assigning a process call returns a **multi-channel object**, not a channel. Access the specific emit name from the TECHNICAL CONTEXT:
- ✗ `step_3(spades_out)` / `spades_out.out` / `spades_out.mix(flye_out)`
- ✓ `step_3(spades_out.assembled)` / `spades_out.assembled.mix(flye_out.assembly)`

**Single unnamed emit exception:** `trimmed = fastp(rawreads).trimmed` works when only one channel is emitted.

## 1B. `.out` Accessor
Without assignment: `snippy(reads, ref)` → access via `snippy.out.bam`
With assignment: `snippy_out = snippy(reads, ref)` → access via `snippy_out.bam`

## 1C. Process Arity
Always match the `take:` signature from the TECHNICAL CONTEXT:
```
step_1PP_hostdepl__bowtie(flatTuple)           // 1 arg
step_2AS_mapping__bowtie(reads, reference)     // 2 args
step_4TY_cgMLST__chewbbaca(asm, species, schema) // 3 args
```

## 1D. Reference Crossing (Mapping Tools)
For Bowtie/Minimap2/Ivar/Snippy — extract `[riscd, code, path]` with `it[1][1..3]`:
```groovy
reads.cross(reference) {{ extractKey(it) }}.multiMap {{
    reads: it[0]
    refs:  it[1][1..3]
}}.set {{ sync }}
step_2AS_mapping__bowtie(sync.reads, sync.refs)
```

## 1E. Host Depletion
Requires **single flat tuple** `[riscd, reads, host]`. Use `.map`, **never** `.multiMap`.

**Conditional:**
```groovy
trimmedReads.cross(host) {{ extractKey(it) }}
    .map {{ [ it[0][0], it[0][1], it[1][1] ] }}
    .branch {{ with_host: it[1][1]; without_host: true }}
    .set {{ branched }}
depleted = step_1PP_hostdepl__bowtie(branched.with_host)
branched.without_host.mix(depleted).map {{ it[0,1] }}.set {{ ready }}
```

**Unconditional:**
```groovy
reads.cross(host) {{ extractKey(it) }}.map {{ [ it[0][0], it[0][1], it[1][1] ] }}.set {{ prep }}
depleted = step_1PP_hostdepl__bowtie(prep)
```

## 1F. Trimming & QC Comparison
```groovy
readsCheckInput = rawreads.cross(trimmed) {{ extractKey(it) }}.multiMap {{
    rawreads: it[0]; trimmed: it[1]
}}
sample_reads_check(readsCheckInput.rawreads, readsCheckInput.trimmed)
```

## 1G. Double Cross (Nested Tuples)
Chained `.cross()` deeply nests — handle indices carefully:
```groovy
assembled.cross(reference) {{ extractKey(it) }}
    .cross(abricateDb) {{ extractKey(it) }}
    .multiMap {{
        assembly: it[0][0][0..1]
        reference: it[0][1]
        abricateDb: it[1]
    }}.set {{ cARA }}
```

## 1H. Static Reference Injection
Define constants in `globals`, attach with `.multiMap`:
```groovy
trimmed.multiMap {{
    trimmed: it
    reference: [ referenceRiscd, referenceCode, file(referencePath) ]
}}.set {{ trAndRef }}
ivar_out = step_2AS_mapping__ivar(trAndRef.trimmed, trAndRef.reference)
```

## 1I. Prokka Injection
Prokka needs `[riscd, assembly, kingdom, riscd_ref, refid, refpath]`:
```groovy
// Bacteria:
step_4AN_genes__prokka(assembly.map {{ [ it[0], it[1], 'Bacteria', '-', '-', getEmpty() ] }})
// Viruses (with GenBank ref):
consensus.cross(referenceGB) {{ extractKey(it) }}.map {{
    [ it[0][0], it[0][1], 'Viruses', it[1][1], it[1][2], it[1][3] ]
}}.set {{ prokkaIn }}
step_4AN_genes__prokka(prokkaIn)
```

## 1J. Snippy Multi-Alignment
Use `.combine()` (not `.cross()`) for shared single reference:
```groovy
reads.combine(reference).multiMap {{ reads: it[0..1]; reference: it[2..4] }}.set {{ input }}
snippy(input.reads, input.reference)
```

## 1K. Technology Branching
```groovy
rawReads.branch {{
    illumina: isIlluminaPaired(it[1])
    ion: isIonTorrent(it[1])
    nanopore: isNanopore(it[1])
    other: true
}}.set {{ ch_tech }}
proc_trim = step_1PP_trimming__trimmomatic(ch_tech.illumina)
proc_fastp = step_1PP_trimming__fastp(ch_tech.ion)
ch_trimmed = proc_trim.trimmed.mix(proc_fastp.trimmed)
```

## 1L. Pre-Shaped Data
If data was already joined upstream, do **not** `.cross()`/`.combine()` again. Pass directly.

## 1M. Coverage & Depth
Use `extractDsRef(it)` for keying:
```groovy
minmax_out = coverage_minmax(samtools_out.bam, 'bowtie')
coverage_plot(minmax_out.coverage_depth)
depth_out = samtools_depth(samtools_out.bam, 'bowtie')
ch_cov_keyed = depth_out.coverage.map {{ [extractDsRef(it), it] }}
ch_con_keyed = consensus.map {{ [extractDsRef(it), it] }}
ch_cov_keyed.cross(ch_con_keyed).map {{
    def cov = it[0][1]; def con = it[1][1]
    return [ cov[0], con[1], cov[1] ]
}}.set {{ coverageRefAndConsensus }}
check_out = coverage_check(coverageRefAndConsensus, 'bowtie')
```

## 1N. Segmented / Multi-Reference
Use `getReferences('any')` (plural) with a `prepare_inputs` sub-workflow:
```groovy
// prepare_inputs body_code:
raw_reads.cross(raw_refs) {{ extractKey(it) }}.multiMap {{
    reads: it[0]; refs: it[1][1..3]
}}.set {{ ch_prepared }}
// entrypoint:
ch_ready = prepare_inputs(ch_in, ch_ref)
module_segmented(ch_ready.reads, ch_ready.refs)
```

---

# 2. Tool Reference

## VOID Tools (no assignment, no emit — publishDir only)
`step_4TY_lineage__pangolin`, `step_4AN_genes__prokka`, `step_4AN_AMR__abricate`, `step_4AN_AMR__staramr`, `step_4AN_AMR__resfinder`, `step_4AN_AMR__filtering`, `step_4TY_MLST__mlst`, `step_4TY_flaA__flaA`, `step_4TY_cgMLST__chewbbaca`, `step_3TX_class__centrifuge`, `step_3TX_class__confindr`, `step_3TX_species__mash`, `step_0SQ_rawreads__fastq`, `step_2AS_mapping__snippy`, `module_qc_fastqc`, `module_qc_nanoplot`, `module_qc_quast`

> If the plan says "emit the report" for a VOID tool, **ignore that instruction**. Just call the process.

## Emitting Tools

| Tool | Emit Channel(s) |
|------|-----------------|
| `step_2AS_mapping__bowtie` | `.consensus` |
| `step_2AS_mapping__ivar` | `.consensus`, `.coverage_depth` |
| `step_2AS_mapping__medaka` | `.consensus` |
| `step_2AS_mapping__minimap2` | `.consensus` |
| `step_2AS_denovo__spades` | `.assembled` |
| `step_2AS_denovo__shovill` | `.assembly` |
| `step_2AS_denovo__unicycler` | `.assembled` |
| `step_2AS_denovo__plasmidspades` | `.assembled` |
| `step_2AS_denovo__metaspades` | `.assembled` |
| `step_2AS_hybrid__unicycler` | `.scaffolds` |
| `step_1PP_trimming__fastp` | `.trimmed` |
| `step_1PP_trimming__trimmomatic` | `.trimmed` |
| `step_1PP_trimming__chopper` | `.trimmed` |
| `step_1PP_hostdepl__bowtie` | direct (unnamed) |
| `step_1PP_hostdepl__minimap2` | direct (unnamed) |
| `step_1PP_filtering__bowtie` | direct (unnamed) |
| `step_1PP_filtering__minimap2` | direct (unnamed) |
| `step_3TX_species__kmerfinder` | `.assigned_species` |
| `step_3TX_class__kraken` | `.genus_report` |
| `step_3TX_class__kraken2` | `.genus_report` |
| `step_3TX_species__vdabricate` | `.calls` |
| `step_4TY_lineage__westnile` | `.lineage` |
| `step_4TY_plasmid__mobsuite` | `.plasmids` |

---

# 3. Globals vs Entrypoint

**`globals`** — static constants only. Always quote values.
- ✓ `{{"type":"def", "name":"refCode", "value":"'NC_045512.2'"}}`
- ✗ `{{"type":"def", "name":"reads", "value":"getSingleInput()"}}` — **crashes Nextflow**

**`entrypoint`** — instantiate ALL active channels here: `getSingleInput()`, `getReference('fa')`, `getHost()`, `getTrimmedReads()`, `getAssembly()`, etc.

---

# 4. Scoping & Emit Rules

- Sub-workflows are **isolated** — they cannot see entrypoint variables.
- Every `take_channels` entry **must** appear in `body_code`.
- `emit_channels`: only variable names or property assignments. No function calls.
  - ✓ `["consensus = ivar_res.consensus"]` (Direct extraction in emit)
  - ✗ `["out = step_2AS_mapping__ivar(reads, refs)"]`
- **NO POINTLESS `.set` ALIASING**: Do NOT use `.set {{}}` just to rename a process output so you can emit it. Handle the extraction directly in the `emit_channels` JSON list!
  - ✗ `body_code`: `kraken_out.genus_report.set {{ genus_report }}`, `emit_channels`: `["genus_report"]`
  - ✓ `body_code`: `kraken_out = step_3TX(...)`, `emit_channels`: `["genus_report = kraken_out.genus_report"]`
- Emit **what you defined**. If you created `prepared_data` via `.map`, emit that — not the raw input.
- **Terminal sub-workflows** (final step): `emit_channels` must be `[]`.
- **Void tools**: never assign to variable, never emit.
  - ✓ `step_4TY_lineage__pangolin(consensus)`
  - ✗ `res = step_4TY_lineage__pangolin(consensus)`
- **No active channels** (`getSingleInput`, `getReference`, etc.) inside sub-workflows. Entrypoint only.

---

# 5. Pipeline Design Rules

- **Group** related steps into cohesive modules (e.g., `module_deplete_and_map`).
- **No single-process wrappers**: if a step is one tool, call it directly in the entrypoint.
- **No double shaping**: if Workflow A already crossed reads+refs, Workflow B must not cross again.
- **One shaping strategy** per data stream — either local (inside sub-workflow) or global (prepare_inputs). Not both.
- **Entrypoint** = orchestrator only. Instantiate channels, connect modules. Cannot emit.
- **QC modules**: use `module_qc_fastqc(reads)`, `module_qc_nanoplot(reads)`, `module_qc_quast(assemblies)` as-is. These are void.

---

# 6. JSON Example

```json
{{
  "imports": [],
  "globals": [
    {{"type": "def", "name": "referenceCode", "value": "'NC_045512.2'"}},
    {{"type": "def", "name": "referencePath", "value": "\"${{params.assets_dir}}/module_covid_emergency/NC_045512.fasta\""}},
    {{"type": "def", "name": "referenceRiscd", "value": "'220308-020220308005121273-2AS_import-external'"}}
  ],
  "inline_processes": [],
  "sub_workflows": [
    {{
      "name": "module_covid_emergency",
      "take_channels": ["trimmed"],
      "emit_channels": [],
      "body_code": "trimmed.multiMap {{\\n    trimmed: it\\n    reference: [ referenceRiscd, referenceCode, file(referencePath) ]\\n}}.set {{ trAndRef }}\\n\\nivar_out = step_2AS_mapping__ivar(trAndRef.trimmed, trAndRef.reference)\\nstep_4TY_lineage__pangolin(ivar_out.consensus)"
    }}
  ],
  "entrypoint": {{
    "body_code": "module_covid_emergency(getSingleInput())"
  }}
}}
```
"""

DIAGRAM_SYSTEM_PROMPT = """You are a Principal Bioinformatics Architect and Technical Documentation Expert.
Your ONLY job is to read a final Nextflow DSL2 script and map its structural data flow into a precise JSON graph object containing `nodes` and `edges`.

# GRAPH MAPPING RULES

## 1. NODE EXTRACTION & SHAPES
You must map EVERY component of the Nextflow script and strictly categorize them into one of these 5 shapes:
* `input`: Use this for starting channels (e.g., `Channel.fromPath(...)`) and for inputs defined in the `take` blocks of sub-workflows.
* `process`: Use this for tool executions (e.g., `step_fastqc(...)`).
* `operator`: Use this for Nextflow channel operators. You MUST create a node for operators like `.map`, `.cross`, `.multiMap`, `.mix`, `.join`, and `.branch`.
* `output`: Use this for final emitted channels (e.g., inside `emit` blocks).
* `global`: Use this for static global variables or constants defined at the top of the script.

## 2. NODE IDs & LABELS (CRITICAL)
* **`id`**: MUST be purely alphanumeric with underscores (e.g., `step_1`, `op_multimap`). **DO NOT use dots, dashes, or spaces in the ID.** * *Wrong:* `step.fastqc`
    * *Right:* `step_fastqc`
* **`label`**: The actual human-readable text. It is okay to use dots or parentheses here (e.g., `.cross`, `reads`, `getSingleInput()`).

## 3. SCOPE & SUBGRAPHS
Nextflow groups logic into `workflow` blocks. You must map this hierarchy using the `subgraph` field:
* If a node is inside a named sub-workflow (e.g., `workflow module_westnile {{ ... }}`), its `subgraph` field must be the workflow name (e.g., `"module_westnile"`).
* If a node is inside the unnamed main entrypoint (`workflow {{ ... }}`), its `subgraph` field must be `"entrypoint"`.
* If a node is defined outside any workflow (like a global variable), leave `subgraph` as `null`.

## 4. EDGES & DATA FLOW (CRITICAL CONNECTIVITY)
You must map how the data flows from `source` to `target`.
* **Connecting Sub-workflows (NO OPAQUE CALLS):** DO NOT create a single process node for a sub-workflow call (e.g., `module_segmented(...)`). Instead, trace the data. Connect the upstream nodes in the entrypoint DIRECTLY to the `input` nodes defined in the `take` block of the sub-workflow.
* **No Floating Nodes:** Every node you create MUST be connected to at least one edge.
* **Edge Labels:** You MUST label the edge with the exact data passing through it.
    * If passing a channel: label it with the channel name (e.g., `"ch_ready"`).
    * If unpacking a tuple: list the contents (e.g., `"val(meta), path(reads)"`).
    * If accessing a process output property: label the specific property (e.g., `"out.consensus"`, `"out.bam"`).
    * If splitting data (like after a `.multiMap`), draw separate edges for each split and label them (e.g., `"reads: it[0]"`).
"""

# ==========================================
# 2. GRAPH NODES
# ==========================================

def consultant_node(state: GraphState, store: BaseStore):
    print("--- [NODE] CONSULTANT (Interactive Planner) ---")
    llm = get_llm()
    
    current_messages = state.get("messages", [])
    latest_query = state.get('user_query', '')
    if current_messages:
        latest_query = current_messages[-1].content

    metadata_context = retrieve_rag_context(latest_query, store, embed_code=False)
    print(f"[Consultant] RAG Context Retrieved: {len(metadata_context)} chars")
    
    print("\n" + "═" * 60)
    print("                 RAG METADATA CONTEXT")
    print("═" * 60)
    print(metadata_context)
    print("═" * 60 + "\n")

    current_plan = state.get("design_plan", "No plan generated yet.")
    current_modules = state.get("selected_module_ids", [])
    
    revision_context = f"""
    # CURRENT PIPELINE STATE
    If you are making a revision, here is the current approved state of the pipeline:
    - Current Modules: {current_modules}
    - Current Plan: {current_plan}
    """
    # --------------------------------

    prompt = ChatPromptTemplate.from_messages([
        ("system", CONSULTANT_SYSTEM_PROMPT + "\n\nAVAILABLE RAG CONTEXT (Tools & Templates):\n{context}\n\n" + revision_context),
        MessagesPlaceholder(variable_name="messages")
    ])

    consultant_agent = llm.with_structured_output(ConsultantOutput)
    chain = prompt | consultant_agent

    try:
        result = chain.invoke({
            "context": metadata_context,
            "messages": current_messages
        })
        
        print(f"[Consultant] Status: {result.status}")

        if result.status == "APPROVED":
            
            # 1. Verify Template ID against the Store
            if result.used_template_id:
                tmpl_item = store.get(("templates",), result.used_template_id)
                if not tmpl_item:
                    print(f"⚠️ Consultant Hallucinated Template ID: '{result.used_template_id}'. Stripping from plan.")
                    result.used_template_id = None
                
            # 2. Verify Component IDs against the Store
            verified_modules = []
            for mod_id in result.selected_module_ids:
                comp_item = store.get(("components",), mod_id)
                if comp_item:
                    verified_modules.append(mod_id)
                else:
                    # Check if they accidentally put a template ID in the module list
                    tmpl_fallback = store.get(("templates",), mod_id)
                    if tmpl_fallback:
                        pass 
                    else:
                        print(f"⚠️ Consultant Hallucinated Module ID: '{mod_id}'. Stripping from plan.")
            
            result.selected_module_ids = verified_modules

        # Detect a "Hard Reset" from the LLM (user asked to start over completely)
        is_hard_reset = (result.status == "CHATTING" and result.draft_plan == "" and len(result.selected_module_ids) == 0)

        # Prepare the baseline state updates
        state_updates = {
            "messages": [AIMessage(content=result.response_to_user)],
            "consultant_status": result.status,
            "design_plan": result.draft_plan if (result.status == "APPROVED" or is_hard_reset) else state.get("design_plan"),
            "strategy_selector": result.strategy_selector if result.status == "APPROVED" else state.get("strategy_selector", "CUSTOM_BUILD"),
            "used_template_id": result.used_template_id if (result.status == "APPROVED" or is_hard_reset) else state.get("used_template_id"),
            "selected_module_ids": result.selected_module_ids if (result.status == "APPROVED" or is_hard_reset) else state.get("selected_module_ids", []),
            "error": None
        }

        # POST-GENERATION REVISION TRIGGER
        # Wipe the old execution data so the frontend knows we are rebuilding or resetting
        if result.status == "CHATTING" or (result.status == "APPROVED" and state.get("nextflow_code")):
            state_updates["nextflow_code"] = None
            state_updates["mermaid_code"] = None
            state_updates["ast_json"] = None

        return state_updates
        
    except Exception as e:
        print(f"💥 Consultant Node Failed: {str(e)}")
        return {"error": f"Consultant Agent Failed: {str(e)}"}


def architect_node(state: GraphState):
    print("--- [NODE] ARCHITECT (Hybrid Code Generator) ---")
    if state.get("error"): return {"error": state['error']}
    
    llm = get_llm()
    architect_agent = llm.with_structured_output(NextflowPipelineAST, method="json_schema", include_raw=False)

    prompt = ChatPromptTemplate.from_messages([
        ("system", ARCHITECT_SYSTEM_PROMPT),
        ("human", "APPROVED PLAN:\n{plan}\n\nTECHNICAL CONTEXT (Available Tools & Code):\n{tech_context}")
    ])
        
    messages = prompt.invoke({
        "plan": state.get('design_plan', 'No plan provided.'),
        "tech_context": state.get('technical_context', 'No context provided.')
    }).to_messages()

    try:
        result = architect_agent.invoke(messages)
        print("[Architect] Successfully generated Hybrid AST.")
        return {
            "ast_json": result.model_dump(),
            "validation_error": None
        }
    except Exception as e:
        print(f"⚠️ Architect Validation Failed: {str(e)}")
        
        raw_ast = {}
        # Attempt best-effort extraction from OutputParserException or ValidationError
        llm_output = getattr(e, "llm_output", None)
        if llm_output and isinstance(llm_output, str):
            import json, re
            try:
                content = llm_output
                match = re.search(r'```(?:json)?\s*(\{.*\})\s*```', content, re.DOTALL)
                if match:
                    content = match.group(1)
                raw_ast = json.loads(content)
            except Exception:
                pass
                
        return {
            "ast_json": raw_ast,
            "validation_error": str(e),
            "retries": state.get("retries", 0) + 1
        }
    

def diagram_node(state: GraphState):
    print("--- [NODE] DIAGRAM AGENT (JSON -> Python Compiler) ---")
    if state.get("error"): return {"error": state['error']}
    
    final_code = state.get("nextflow_code", "")
    if not final_code:
        print("[Diagram] Warning: No Nextflow code found.")
        return {"mermaid_code": "flowchart TD\n    Empty[No code generated]"}

    llm = get_llm()
    diagram_agent = llm.with_structured_output(DiagramData, method="json_schema", include_raw=False)

    prompt = ChatPromptTemplate.from_messages([
        ("system", DIAGRAM_SYSTEM_PROMPT),
        ("human", "Map this Nextflow code into a JSON Node/Edge Graph:\n\n{code}")
    ])
        
    messages = prompt.invoke({"code": final_code}).to_messages()

    max_retries = 3
    for attempt in range(max_retries):
        try:
            result = diagram_agent.invoke(messages)
            
            if not result or not result.nodes:
                raise ValueError("LLM returned empty graph data.")

            mermaid_string = render_mermaid_from_json(result)
            
            print(f"[Diagram] Successfully compiled Mermaid graph on attempt {attempt + 1}.")
            return {"mermaid_code": mermaid_string}
            
        except Exception as e:
            print(f"⚠️ Diagram Data Error (Attempt {attempt + 1}): {str(e)}")
            messages.append(AIMessage(content="I generated an invalid JSON graph structure."))
            messages.append(HumanMessage(content=f"Validation Error: {str(e)}\nFix the data and try again."))
    
    return {"mermaid_code": "flowchart TD\n    Error[\"Diagram generation failed after 3 attempts. See logs for details.\"]"}
    
def filter_template_logic(code: str, allowed_components: set) -> str:
    lines = code.split('\n')
    filtered_lines = []
    
    pattern = re.compile(r'\b((?:step_|module_|multi_)[a-zA-Z0-9_]+)\s*\(')
    
    for line in lines:
        match = pattern.search(line)
        if match:
            func_name = match.group(1)
            
            if func_name not in allowed_components:
                filtered_lines.append(f"    // [REMOVED BY PLAN] {line.strip()}")
                continue
        
        filtered_lines.append(line)
        
    return "\n".join(filtered_lines)

def hydrator_node(state: GraphState, store: BaseStore):
    print("--- [NODE] HYDRATOR (Context Assembly) ---")

    if state.get("error"):
        return {"error": state["error"]}
    
    context_parts = []
    detected_helpers = set()

    strategy = state.get('strategy_selector', 'CUSTOM_BUILD')
    used_template_id = state.get('used_template_id')
    module_ids = state.get('selected_module_ids', [])
    plan_text = state.get('design_plan', '')

    # Access Data from Store
    RES_ITEM = store.get(("resources",), "helper_functions")

    RES_LIST = RES_ITEM.value.get("list", []) if RES_ITEM else []

    helper_names = [r['name'] for r in RES_LIST]

    # ==========================================
    # PATH A: STRICT TEMPLATE MODE
    # ==========================================
    if strategy == "EXACT_MATCH" and used_template_id:
        tmpl_id = used_template_id
        tmpl_item = store.get(("templates",), tmpl_id)
        template_def = tmpl_item.value if tmpl_item else None

        context_parts.append(f"### STRICT TEMPLATE MODE: {tmpl_id}")
        if template_def:
            context_parts.append(f"Description: {template_def.get('description')}")
            
            code_item = store.get(("code",), tmpl_id)

            # print("code_item", code_item)

            tmpl_code = code_item.value.get("content") if code_item else None

            # print("tmpl_code", tmpl_code)
            
            if tmpl_code:
                context_parts.append(f"[[TEMPLATE SOURCE CODE: {tmpl_id}]]")
                context_parts.append("INSTRUCTION: Use the logic in this workflow block exactly.")
                context_parts.append(f"```groovy\n{tmpl_code.strip()}\n```")
                context_parts.append(f"[[END TEMPLATE SOURCE]]")
                
                for h in helper_names:
                    if h in tmpl_code: detected_helpers.add(h)
            
            for step in template_def.get('logic_flow', []):
                if 'step' in step:
                    comp_id = step['step']
                    c_item = store.get(("code",), comp_id)
                    code = c_item.value.get("content") if c_item else None
                    if code:
                        context_parts.append(f"[[REFERENCE FOR STEP: {comp_id}]]")
                        context_parts.append(f"```groovy\n{code.strip()}\n```")
                        context_parts.append(f"[[END REFERENCE]]")
                        
                        for h in helper_names:
                            if h in code: detected_helpers.add(h)

    # ==========================================
    # PATH B: ADAPTED OR CUSTOM MODE
    # ==========================================
    else:
        if strategy == "ADAPTED_MATCH" and used_template_id:
            context_parts.append(f"### ADAPTED TEMPLATE MODE: Based on {used_template_id}")
            t_item = store.get(("code",), used_template_id)
            tmpl_code = t_item.value.get("content") if t_item else None

            if tmpl_code:
                # We combine the template ID and the new module IDs into the allowed list
                allowed_ids = set([used_template_id] + module_ids)
                
                filtered_code = filter_template_logic(tmpl_code, allowed_ids)

                context_parts.append(f"[[TEMPLATE SOURCE CODE: {used_template_id}]]")
                context_parts.append("INFO: Some steps in this template have been commented out because they are not in your Design Plan.")
                context_parts.append("INSTRUCTION: Reuse the logic that remains, but FILL THE GAPS using your new components.")
                context_parts.append(f"```groovy\n{filtered_code.strip()}\n```")
                
                for h in helper_names:
                    if h in tmpl_code: detected_helpers.add(h)        
        else:
            context_parts.append("### CUSTOM BUILD MODE")

        # We loop through the simple list of strings now
        for comp_id in module_ids:
            if comp_id == used_template_id and strategy == "ADAPTED_MATCH":
                continue

            code_item = store.get(("code",), comp_id)
            source_code = code_item.value.get("content") if code_item else None
            
            if source_code:
                context_parts.append(f"[[REFERENCE FOR STEP: {comp_id}]]")
                context_parts.append(f"Component ID: {comp_id}")
                context_parts.append(f"```groovy\n{source_code.strip()}\n```")
                context_parts.append(f"[[END REFERENCE: {comp_id}]]")
                for h in helper_names:
                    if h in source_code: detected_helpers.add(h)

    # ==========================================
    # RESOURCE INJECTION
    # ==========================================
    if plan_text and ("cross" in plan_text or "multiMap" in plan_text):
        detected_helpers.add("extractKey")
    
    if detected_helpers:
        context_parts.append("\n### AVAILABLE HELPER FUNCTIONS")
        for h_name in detected_helpers:
            res_def = next((r for r in RES_LIST if r['name'] == h_name), None)
            if res_def:
                context_parts.append(f"- {h_name}: {res_def.get('description')}")
                context_parts.append(f"  Usage: `{res_def.get('usage')}`")
                
    full_context = "\n\n".join(context_parts)
    # print(f"technical_context: {full_context}")

    return {"technical_context": full_context}