services:
  api:
    build: .
    container_name: api_test
    restart: always
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}

  # The HTTPS Server
  caddy:
    image: caddy:latest
    container_name: caddy_test
    restart: always
    ports:
      - "8081:80" # HTTP
      - "8443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_test:/data
      - caddy_config_test:/config
    depends_on:
      - api

volumes:
  caddy_data_test:
  caddy_config_test:
