"""
tests/scenarios/level3_complex.py
Level 3 — Complex: Multi-step pipeline construction

Each scenario requires the system to chain 3+ tools into a coherent pipeline,
handling channel wiring, multi-step data flow, and cross-domain analysis.

Complexity: COMPLEX
  - User describes a multi-step analysis spanning 3+ bioinformatics domains
  - Requires correct channel routing between steps
  - May need custom pipeline construction (no single template covers it)
  - Expected: system builds a complete, functional multi-step pipeline
"""

import os

LEVEL3_SCENARIOS = [
    {
        "id": "L3_01_bacteria_typing_full",
        "level": 3,
        "difficulty": "complex",
        "description": "Bacterial isolate characterization: species ID + MLST + AMR",
        "chat_messages": [
            "I have bacterial Illumina isolates from a foodborne outbreak. I need to identify the species, run MLST for epidemiological typing, and find antimicrobial resistance genes.",
            "The isolates are Campylobacter jejuni. I have paired-end 2x150bp Illumina reads, already trimmed.",
            "Yes, I want KmerFinder for species, MLST for sequence typing, and ABRicate for AMR screening. That covers everything I need.",
            "I approve. Build the pipeline.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
        "template_ids": [],
        "component_ids": ["step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute a custom pipeline. Step 1: Species ID with KmerFinder. Step 2: Sequence typing with MLST. Step 3: AMR screening with ABRicate.",
        "selected_module_ids": ["step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
    },
    {
        "id": "L3_02_viral_genome_reconstruction",
        "level": 3,
        "difficulty": "complex",
        "description": "Viral genome reconstruction: mapping + consensus + Prokka annotation",
        "chat_messages": [
            "I want to reconstruct a viral genome from Illumina reads. I need reference mapping, consensus generation, and then gene annotation with Prokka.",
            "It's a flavivirus sample. I have the reference FASTA and GenBank files ready. The reads are paired-end Illumina, already trimmed.",
            "Yes, use iVar for mapping and consensus, then Prokka for annotation. I approve, please build.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_draft_genome", "step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
        "template_ids": ["module_draft_genome"],
        "component_ids": ["step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_draft_genome",
        "design_plan": "Execute viral draft genome pipeline. Step 1: Mapping and consensus generation with iVar. Step 2: Gene annotation with Prokka.",
        "selected_module_ids": ["step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
    },
    {
        "id": "L3_03_selective_assembly",
        "level": 3,
        "difficulty": "complex",
        "description": "Extract mapped reads + de novo assembly of selected fraction",
        "chat_messages": [
            "I have a mixed clinical sample with host contamination. I want to extract only the reads that map to a specific pathogen reference, then assemble only those reads de novo.",
            "It's an Illumina paired-end sample. I have the pathogen reference FASTA. I want to use Bowtie2 for filtering, then SPAdes for assembly.",
            "Yes, that's the workflow I need. Filter first, then assemble the filtered reads. I approve.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_filtered_denovo", "step_2AS_mapping__bowtie", "step_2AS_denovo__spades"],
        "template_ids": ["module_filtered_denovo"],
        "component_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_filtered_denovo",
        "design_plan": "Execute selective filtering de novo pipeline. Step 1: Map to pathogen reference with Bowtie2 to extract mapped reads. Step 2: Assemble mapped reads with SPAdes.",
        "selected_module_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades"],
    },
    {
        "id": "L3_04_trim_assemble_amr",
        "level": 3,
        "difficulty": "complex",
        "description": "Trimming + de novo assembly + AMR detection: fastp → SPAdes → ABRicate",
        "chat_messages": [
            "I want to trim Illumina reads with fastp, do de novo assembly with SPAdes, and then run ABRicate for AMR gene detection on the assemblies.",
            "Yes, the reads are raw paired-end Illumina from bacterial isolates. I need all three steps chained together.",
            "I approve. Build the full pipeline.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_2AS_denovo__spades", "step_4AN_AMR__abricate"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__spades", "step_4AN_AMR__abricate"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute custom pipeline. Step 1: Trim reads with fastp. Step 2: Assemble with SPAdes. Step 3: Run AMR detection with ABRicate on assemblies.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__spades", "step_4AN_AMR__abricate"],
    },
    {
        "id": "L3_05_bacteria_full_workflow",
        "level": 3,
        "difficulty": "complex",
        "description": "Full bacterial workflow: trim → assemble → species ID → MLST",
        "chat_messages": [
            "I have bacterial isolates from environmental monitoring. I need a complete workflow: trim with fastp, assemble with Shovill, identify species with KmerFinder, and run MLST.",
            "The samples are Listeria monocytogenes from a food processing plant. Illumina paired-end reads.",
            "Yes, all four steps in sequence. I approve, build it.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_2AS_denovo__shovill", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__shovill", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute custom pipeline. Step 1: Trim with fastp. Step 2: Assemble with Shovill. Step 3: Identify species with KmerFinder. Step 4: Run MLST.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__shovill", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst"],
    },
    {
        "id": "L3_06_hostdepl_assemble_annotate",
        "level": 3,
        "difficulty": "complex",
        "description": "Host depletion + assembly + annotation: Bowtie → SPAdes → Prokka",
        "chat_messages": [
            "I want to do host depletion with Bowtie, then assemble the depleted reads with SPAdes, and annotate the assembled contigs with Prokka.",
            "The host is bovine (Bos taurus). The sample is from a clinical veterinary case. Illumina paired-end reads.",
            "Yes, host depletion first, then assembly, then annotation. I approve.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades", "step_4AN_genes__prokka"],
        "template_ids": [],
        "component_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades", "step_4AN_genes__prokka"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute custom pipeline. Step 1: Deplete host reads with Bowtie. Step 2: Assemble with SPAdes. Step 3: Annotate contigs with Prokka.",
        "selected_module_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades", "step_4AN_genes__prokka"],
    },
    {
        "id": "L3_RECREATION_REV_01_draft_genome_bowtie_to_ivar",
        "level": 3,
        "difficulty": "complex",
        "description": "Revision: draft genome mapping switched to iVar",
        "chat_messages": [
            "I have some bacterial short reads and a reference genome. I want to map the reads and build a consensus. After that I need to find the genes.",
            "Approved.",
            "Please change the mapping tool from bowtie to ivar.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_draft_genome", "step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
        "template_ids": ["module_draft_genome"],
        "component_ids": ["step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "must_include_final": ["ivar", "prokka"],
        "design_plan": "Execute revised draft genome workflow. Step 1: Build consensus with iVar mapping. Step 2: Annotate genes with Prokka.",
        "selected_module_ids": ["step_2AS_mapping__ivar", "step_4AN_genes__prokka"],
    },
    {
        "id": "L3_RECREATION_REV_02_typing_bacteria_abricate_to_staramr",
        "level": 3,
        "difficulty": "complex",
        "description": "Revision: typing bacteria AMR switched to StarAMR",
        "chat_messages": [
            "I have bacterial assemblies. I need to find the genes and amr resistance. I also want to run mlst.",
            "Approved.",
            "I want to use staramr instead of abricate for the amr step.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_typing_bacteria", "step_4AN_genes__prokka", "step_4AN_AMR__staramr", "step_4TY_MLST__mlst"],
        "template_ids": ["module_typing_bacteria"],
        "component_ids": ["step_4AN_genes__prokka", "step_4AN_AMR__staramr", "step_4TY_MLST__mlst"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "must_include_final": ["staramr", "mlst", "prokka"],
        "design_plan": "Execute revised typing workflow. Step 1: Annotation with Prokka. Step 2: AMR with StarAMR. Step 3: Sequence typing with MLST.",
        "selected_module_ids": ["step_4AN_genes__prokka", "step_4AN_AMR__staramr", "step_4TY_MLST__mlst"],
    },
    {
        "id": "L3_RECREATION_REV_03_cfsan_add_iqtree",
        "level": 3,
        "difficulty": "complex",
        "description": "Revision: cfsan workflow extended with phylogeny",
        "chat_messages": [
            "I have some fastq files and a reference. I want to run a snp pipeline to find mutations.",
            "Approved.",
            "Please build a tree with the results after the pipeline using iqtree.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_cfsan"],
        "template_ids": ["module_cfsan"],
        "component_ids": [],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_cfsan",
        "must_include_final": ["iqtree"],
        "design_plan": "Execute cfsan SNP workflow and include tree-building with iqtree on resulting variation profiles.",
        "selected_module_ids": [],
    },
]

_LEGACY_LEVEL3_SCENARIOS = LEVEL3_SCENARIOS
NEW_LEVEL3_SCENARIOS = [
    {
        "id": "L3_18_full_nanopore_isolate",
        "level": 3,
        "difficulty": "complex",
        "description": "Comprehensive Nanopore isolate pipeline",
        "chat_messages": [
            "I need a complete Nanopore pipeline: trim with Chopper, assemble with Flye, annotate with Prokka, run MLST, and screen AMR with ABRicate.",
            "Yes, chain all those steps.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__chopper", "step_2AS_denovo__flye", "step_4AN_genes__prokka", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__chopper", "step_2AS_denovo__flye", "step_4AN_genes__prokka", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute a custom isolate pipeline. Step 1: Trim Nanopore reads with Chopper. Step 2: Assemble with Flye. Step 3: Annotate with Prokka. Step 4: Run MLST. Step 5: AMR with ABRicate.",
        "selected_module_ids": ["step_1PP_trimming__chopper", "step_2AS_denovo__flye", "step_4AN_genes__prokka", "step_4TY_MLST__mlst", "step_4AN_AMR__abricate"],
    },
    {
        "id": "L3_19_mixed_sample_extraction",
        "level": 3,
        "difficulty": "complex",
        "description": "Host depletion, classification, taxa extraction, and assembly",
        "chat_messages": [
            "Process a mixed sample with Bowtie host depletion, classify remaining reads with Kraken2, extract target taxa with Krakentools, then assemble with Shovill.",
            "Approved.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_hostdepl__bowtie", "step_3TX_class__kraken2", "step_1PP_filtering__krakentools", "step_2AS_denovo__shovill"],
        "template_ids": [],
        "component_ids": ["step_1PP_hostdepl__bowtie", "step_3TX_class__kraken2", "step_1PP_filtering__krakentools", "step_2AS_denovo__shovill"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute mixed-sample workflow. Step 1: Host depletion with Bowtie2. Step 2: Classification with Kraken2. Step 3: Target extraction with Krakentools. Step 4: Assembly with Shovill.",
        "selected_module_ids": ["step_1PP_hostdepl__bowtie", "step_3TX_class__kraken2", "step_1PP_filtering__krakentools", "step_2AS_denovo__shovill"],
    },
    {
        "id": "L3_20_viral_variant_pipeline",
        "level": 3,
        "difficulty": "complex",
        "description": "SARS-CoV-2 trim, map, consensus, and lineage",
        "chat_messages": [
            "For SARS-CoV-2, trim reads with fastp, map with Bowtie2, generate consensus with iVar, and assign lineage with Pangolin.",
            "Yes, build that exact workflow.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_2AS_mapping__bowtie", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_2AS_mapping__bowtie", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute SARS-CoV-2 variant workflow. Step 1: fastp trimming. Step 2: Bowtie2 mapping. Step 3: iVar consensus. Step 4: Pangolin lineage.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_2AS_mapping__bowtie", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
    },
    {
        "id": "L3_21_bacterial_population_typing",
        "level": 3,
        "difficulty": "complex",
        "description": "Downsampling, assembly, cgMLST, and AMR",
        "chat_messages": [
            "Analyze a bacterial population by downsampling with bbnorm, assembling with SPAdes, running cgMLST with ChewBBACA, and screening AMR with ABRicate.",
            "Approved.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_downsampling__bbnorm", "step_2AS_denovo__spades", "step_4TY_cgMLST__chewbbaca", "step_4AN_AMR__abricate"],
        "template_ids": [],
        "component_ids": ["step_1PP_downsampling__bbnorm", "step_2AS_denovo__spades", "step_4TY_cgMLST__chewbbaca", "step_4AN_AMR__abricate"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute population workflow. Step 1: Downsampling with bbnorm. Step 2: SPAdes assembly. Step 3: cgMLST with chewBBACA. Step 4: AMR with ABRicate.",
        "selected_module_ids": ["step_1PP_downsampling__bbnorm", "step_2AS_denovo__spades", "step_4TY_cgMLST__chewbbaca", "step_4AN_AMR__abricate"],
    },
    {
        "id": "L3_22_deep_metagenomics_annotation",
        "level": 3,
        "difficulty": "complex",
        "description": "Deep metagenomics workflow with assembly and annotation",
        "chat_messages": [
            "Run deep metagenomics: trim with fastp, classify with centrifuge, assemble with metaspades, annotate contigs with Prokka, and screen AMR with ABRicate.",
            "Yes, proceed.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_3TX_class__centrifuge", "step_2MG_denovo__metaspades", "step_4AN_genes__prokka", "step_4AN_AMR__abricate"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_3TX_class__centrifuge", "step_2MG_denovo__metaspades", "step_4AN_genes__prokka", "step_4AN_AMR__abricate"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute deep metagenomics workflow. Step 1: fastp trimming. Step 2: Centrifuge classification. Step 3: metaSPAdes assembly. Step 4: Prokka annotation. Step 5: ABRicate AMR screening.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_3TX_class__centrifuge", "step_2MG_denovo__metaspades", "step_4AN_genes__prokka", "step_4AN_AMR__abricate"],
    },
    {
        "id": "L3_23_campylobacter_complete",
        "level": 3,
        "difficulty": "complex",
        "description": "Comprehensive Campylobacter typing and AMR",
        "chat_messages": [
            "Process Campylobacter isolates by trimming with fastp, assembling with Unicycler, confirming species with KmerFinder, typing with MLST and flaA, and running StarAMR.",
            "Approved.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_2AS_denovo__unicycler", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4TY_flaA__flaA", "step_4AN_AMR__staramr"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__unicycler", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4TY_flaA__flaA", "step_4AN_AMR__staramr"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute complete Campylobacter workflow. Step 1: fastp. Step 2: Unicycler assembly. Step 3: KmerFinder species ID. Step 4: MLST and flaA typing. Step 5: StarAMR.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_2AS_denovo__unicycler", "step_3TX_species__kmerfinder", "step_4TY_MLST__mlst", "step_4TY_flaA__flaA", "step_4AN_AMR__staramr"],
    },
    {
        "id": "L3_24_plasmid_amr_tracking",
        "level": 3,
        "difficulty": "complex",
        "description": "Plasmid reconstruction, typing, AMR, and annotation",
        "chat_messages": [
            "Track plasmids and AMR by trimming with Trimmomatic, running plasmidspades, typing plasmids with Mobsuite, screening AMR with ABRicate, and annotating with Prokka.",
            "Approved.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__trimmomatic", "step_2AS_denovo__plasmidspades", "step_4TY_plasmid__mobsuite", "step_4AN_AMR__abricate", "step_4AN_genes__prokka"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__trimmomatic", "step_2AS_denovo__plasmidspades", "step_4TY_plasmid__mobsuite", "step_4AN_AMR__abricate", "step_4AN_genes__prokka"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute plasmid tracking workflow. Step 1: Trimmomatic. Step 2: plasmidSPAdes. Step 3: Mobsuite. Step 4: ABRicate AMR. Step 5: Prokka annotation.",
        "selected_module_ids": ["step_1PP_trimming__trimmomatic", "step_2AS_denovo__plasmidspades", "step_4TY_plasmid__mobsuite", "step_4AN_AMR__abricate", "step_4AN_genes__prokka"],
    },
    {
        "id": "L3_25_westnile_comprehensive",
        "level": 3,
        "difficulty": "complex",
        "description": "West Nile trimming, host depletion, lineage and consensus",
        "chat_messages": [
            "For West Nile Virus samples, trim with fastp, remove host reads with Bowtie host depletion, then determine lineage with westnile and generate consensus with iVar.",
            "Yes, build it.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_1PP_trimming__fastp", "step_1PP_hostdepl__bowtie", "step_4TY_lineage__westnile", "step_2AS_mapping__ivar"],
        "template_ids": [],
        "component_ids": ["step_1PP_trimming__fastp", "step_1PP_hostdepl__bowtie", "step_4TY_lineage__westnile", "step_2AS_mapping__ivar"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute comprehensive WNV workflow. Step 1: fastp trimming. Step 2: host depletion with Bowtie2. Step 3: lineage with westnile. Step 4: consensus mapping with iVar.",
        "selected_module_ids": ["step_1PP_trimming__fastp", "step_1PP_hostdepl__bowtie", "step_4TY_lineage__westnile", "step_2AS_mapping__ivar"],
    },
]

OLD_LEVEL3_TEST_IDS = [s["id"] for s in _LEGACY_LEVEL3_SCENARIOS]
NEW_LEVEL3_TEST_IDS = [s["id"] for s in NEW_LEVEL3_SCENARIOS]


def _env_enabled(var_name: str) -> bool:
    return os.getenv(var_name, "").strip().lower() in {"1", "true", "yes", "on"}


if _env_enabled("ONLY_NEW_SCENARIOS"):
    print("[tests] ONLY_NEW_SCENARIOS is enabled: not testing old Level 3 scenarios.")
    LEVEL3_SCENARIOS = NEW_LEVEL3_SCENARIOS
else:
    LEVEL3_SCENARIOS = _LEGACY_LEVEL3_SCENARIOS + NEW_LEVEL3_SCENARIOS

DEFAULT_EXPECTED_TOOL_CALLS = ["search_components", "verify_component_id"]

for _scenario in LEVEL3_SCENARIOS:
    _scenario.setdefault("expected_tool_calls", DEFAULT_EXPECTED_TOOL_CALLS)
